# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /usr/local/bin/Linux_Unreal_Engine_5.2.0
GAMEPROJECTFILE =/home/liminal/Documents/Unreal Projects/RollerBall/RollerBall.uproject

TARGETS = \
	RollerBall-Linux-DebugGame  \
	RollerBall-Linux-Shipping  \
	RollerBall \
	RollerBallEditor-Linux-DebugGame  \
	RollerBallEditor-Linux-Shipping  \
	RollerBallEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RollerBallEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RollerBallEditor-Linux-Debug


RollerBall-Linux-DebugGame:
	 $(PROJECTBUILD) RollerBall Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RollerBall-Linux-Shipping:
	 $(PROJECTBUILD) RollerBall Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RollerBall:
	 $(PROJECTBUILD) RollerBall Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

RollerBallEditor-Linux-DebugGame:
	 $(PROJECTBUILD) RollerBallEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RollerBallEditor-Linux-Shipping:
	 $(PROJECTBUILD) RollerBallEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RollerBallEditor:
	 $(PROJECTBUILD) RollerBallEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
